/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class halamanInfoPesanan extends javax.swing.JPanel {

    /**
     * Creates new form halamanInfoPesanan
     */
    public halamanInfoPesanan() {
        initComponents();
        loadTableData();
    }
    public void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        if (userData.allAppointments != null) {
            for (userData.Appointment app : userData.allAppointments) {
                model.addRow(new Object[]{
                    app.namaPasien,
                    app.nim,
                    app.keluhan,
                    app.dokter,
                    app.hari,
                    app.waktu,
                    app.status 
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INFO PESANAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-planner2.gif"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIM", "Keluhan", "Dokter", "Hari", "Jam", "Keterangan"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if (row >= 0) {
            userData.Appointment app = userData.allAppointments.get(row);
            if (app.status.equalsIgnoreCase("Menunggu")) {
                int response = JOptionPane.showConfirmDialog(this, 
                        "Setujui pesanan ini?\nPasien: " + app.namaPasien, 
                        "Konfirmasi", JOptionPane.YES_NO_OPTION);
                
                if (response == JOptionPane.YES_OPTION) {
                    
                    app.status = "Terkonfirmasi"; 
                    app.pernahDikonfirmasi = true; 
                    
                    loadTableData(); 
                    JOptionPane.showMessageDialog(this, "Status diubah jadi Terkonfirmasi.");
                }
            } 
            else if (app.status.equalsIgnoreCase("Pengajuan Batal")) {
                 int response = JOptionPane.showConfirmDialog(this, 
                        "Setujui pembatalan?", 
                        "Konfirmasi", JOptionPane.YES_NO_OPTION);

                 if (response == JOptionPane.YES_OPTION) {
                    app.status = "Dibatalkan"; 
                    loadTableData();
                 }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void kirimNotifikasiKeUser(String namaTarget, String judul, String detail) {
        boolean userDitemukan = false;

        System.out.println("Mencari user dengan nama: " + namaTarget); 
        
        if (userData.users != null) {
            for (userData.User u : userData.users) {
                if (u.username.equalsIgnoreCase(namaTarget)) {
                    if (u.notifications == null) {
                        u.notifications = new java.util.ArrayList<>();
                    }
                    u.notifications.add(new userData.Notification(judul, detail));
                    userDitemukan = true;
                    System.out.println("Notifikasi berhasil disimpan ke user: " + u.username); 
                    break; 
                }
            }
        }
        if (userData.currentUser != null && userData.currentUser.username.equalsIgnoreCase(namaTarget)) {
            if (userData.currentUser.notifications == null) {
                userData.currentUser.notifications = new java.util.ArrayList<>();
            }
            userData.currentUser.notifications.add(new userData.Notification(judul, detail));
        }
        if (!userDitemukan) {           
            System.out.println("GAGAL: User " + namaTarget + " tidak ditemukan di database userData.users.");
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal mengirim notifikasi. User '" + namaTarget + "' tidak ditemukan di database.",
                "Error Sistem", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
