/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class halamanNotifikasi extends javax.swing.JFrame {
    
    private menuDashboard dashboardUtama;
    private class ItemNotif {
        userData.Appointment app;
        String tipe; 
        public ItemNotif(userData.Appointment app, String tipe) {
            this.app = app;
            this.tipe = tipe;
        }
    }
    private ArrayList<ItemNotif> listTampil = new ArrayList<>();

    public halamanNotifikasi(menuDashboard dashboard) {
        this.dashboardUtama = dashboard; 
        initComponents();
        this.setLocationRelativeTo(null);
        
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                if (row >= 0) {
                    bacaPesan(row);
                }
            }
        });
        
        loadTableData();
    }
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        listTampil.clear(); 

        if (userData.currentUser != null) {
            for (userData.Appointment app : userData.currentUser.appointments) {               
                boolean tampilkanPesanKonfirmasi = false;              
                if (app.status.equalsIgnoreCase("Terkonfirmasi") || app.status.equalsIgnoreCase("Pengajuan Batal")) {
                    tampilkanPesanKonfirmasi = true;
                } 
                else if (app.status.equalsIgnoreCase("Dibatalkan") && app.pernahDikonfirmasi == true) {
                    tampilkanPesanKonfirmasi = true;
                }
                if (tampilkanPesanKonfirmasi) {
                    String statusBaca = (app.isRead) ? "Sudah dibaca" : "Belum dibaca";
                    
                    model.addRow(new Object[]{
                        "Jadwal dengan " + app.dokter + " DISETUJUI Admin!", 
                        "Terkonfirmasi", 
                        statusBaca 
                    });
                    listTampil.add(new ItemNotif(app, "KONFIRMASI"));
                }               
                if (app.status.equalsIgnoreCase("Dibatalkan")) {
                    String statusBacaBatal = (app.isReadPembatalan) ? "Sudah dibaca" : "Belum dibaca";
                    
                    String isiPesan = "Pembatalan jadwal " + app.dokter + " BERHASIL.";
                    
                    model.addRow(new Object[]{
                        isiPesan, 
                        "Dibatalkan",
                        statusBacaBatal 
                    });
                    listTampil.add(new ItemNotif(app, "BATAL"));
                }
            }
        }
    }
    private void bacaPesan(int row) {
        ItemNotif item = listTampil.get(row);
        userData.Appointment app = item.app;
        boolean adaPerubahan = false;
        if (item.tipe.equals("KONFIRMASI")) {
            if (app.isRead == false) {
                app.isRead = true;
                adaPerubahan = true;
            }
        } else if (item.tipe.equals("BATAL")) {
            if (app.isReadPembatalan == false) {
                app.isReadPembatalan = true;
                adaPerubahan = true;
            }
        }
        if (adaPerubahan) {
            if (dashboardUtama != null) {
                dashboardUtama.updateNotificationBadge();
            }
            loadTableData();
        }
        String pesan = jTable1.getValueAt(row, 0).toString();
        String status = jTable1.getValueAt(row, 1).toString();

        JOptionPane.showMessageDialog(this, 
                "Detail Pesan:\n" + pesan + "\n\nStatus Tiket: " + status, 
                "Info Notifikasi", 
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-laptop-alert.gif"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pesan", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText(" Notifikasi Masuk :");

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addGap(0, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (dashboardUtama != null) {
            dashboardUtama.updateNotificationBadge();
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
