/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class halamanHomeAdmin extends javax.swing.JFrame {
    String menuActive = "dashboard";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(halamanHomeAdmin.class.getName());

    /**
     * Creates new form halamanDashboardAdmin
     */
    public halamanHomeAdmin() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    void resetWarna() {
    java.awt.Color warnaDefault = new java.awt.Color(0, 204, 204);
    java.awt.Color warnaPutih = new java.awt.Color(255, 255, 255);
    
    paneMain.setBackground(warnaDefault);
    paneMain1.setBackground(warnaDefault);
    paneMain2.setBackground(warnaDefault);

    panelLain.setBackground(warnaPutih);
    panelLain1.setBackground(warnaPutih);
    panelLain2.setBackground(warnaPutih);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        paneMain = new javax.swing.JPanel();
        panelLain = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttonDashboard = new javax.swing.JLabel();
        paneMain1 = new javax.swing.JPanel();
        panelLain1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buttonOrder = new javax.swing.JLabel();
        paneMain2 = new javax.swing.JPanel();
        panelLain2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buttonJadwalDokter = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKiri.setBackground(new java.awt.Color(255, 255, 255));
        panelKiri.setPreferredSize(new java.awt.Dimension(300, 600));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Menu Apikasi");

        paneMain.setBackground(new java.awt.Color(0, 204, 204));
        paneMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneMainMousePressed(evt);
            }
        });

        panelLain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLainLayout = new javax.swing.GroupLayout(panelLain);
        panelLain.setLayout(panelLainLayout);
        panelLainLayout.setHorizontalGroup(
            panelLainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelLainLayout.setVerticalGroup(
            panelLainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-dashboard-30.png"))); // NOI18N

        buttonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(102, 102, 102));
        buttonDashboard.setText("Profil Admin");
        buttonDashboard.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                buttonDashboardAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        buttonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneMainLayout.createSequentialGroup()
                    .addComponent(panelLain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 276, Short.MAX_VALUE)))
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneMain1.setBackground(new java.awt.Color(0, 204, 204));

        panelLain1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLain1Layout = new javax.swing.GroupLayout(panelLain1);
        panelLain1.setLayout(panelLain1Layout);
        panelLain1Layout.setHorizontalGroup(
            panelLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelLain1Layout.setVerticalGroup(
            panelLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-order-30.png"))); // NOI18N

        buttonOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonOrder.setForeground(new java.awt.Color(102, 102, 102));
        buttonOrder.setText("Jadwalkan Dokter");
        buttonOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonOrderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneMain1Layout = new javax.swing.GroupLayout(paneMain1);
        paneMain1.setLayout(paneMain1Layout);
        paneMain1Layout.setHorizontalGroup(
            paneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMain1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(paneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneMain1Layout.createSequentialGroup()
                    .addComponent(panelLain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 276, Short.MAX_VALUE)))
        );
        paneMain1Layout.setVerticalGroup(
            paneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(buttonOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelLain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneMain2.setBackground(new java.awt.Color(0, 204, 204));

        panelLain2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLain2Layout = new javax.swing.GroupLayout(panelLain2);
        panelLain2.setLayout(panelLain2Layout);
        panelLain2Layout.setHorizontalGroup(
            panelLain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelLain2Layout.setVerticalGroup(
            panelLain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-timetable-30.png"))); // NOI18N

        buttonJadwalDokter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonJadwalDokter.setForeground(new java.awt.Color(102, 102, 102));
        buttonJadwalDokter.setText("Info Pesanan");
        buttonJadwalDokter.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                buttonJadwalDokterAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        buttonJadwalDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonJadwalDokterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonJadwalDokterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonJadwalDokterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneMain2Layout = new javax.swing.GroupLayout(paneMain2);
        paneMain2.setLayout(paneMain2Layout);
        paneMain2Layout.setHorizontalGroup(
            paneMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMain2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonJadwalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneMain2Layout.createSequentialGroup()
                    .addComponent(panelLain2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 276, Short.MAX_VALUE)))
        );
        paneMain2Layout.setVerticalGroup(
            paneMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMain2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(buttonJadwalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelLain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoApp.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("SISTEM INFORMASI KLINIK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foto.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelKiriLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(paneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneMain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneMain2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        getContentPane().add(panelKiri, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDashboardAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_buttonDashboardAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDashboardAncestorAdded

    private void buttonDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseClicked
        menuActive = "dashboard";        
        resetWarna();
        paneMain.setBackground(new java.awt.Color(250, 250, 250));
        panelLain.setBackground(new java.awt.Color(0, 102, 153));       
        jPanel5.removeAll(); 
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(new halamanProfilAdmin(), java.awt.BorderLayout.CENTER);        
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_buttonDashboardMouseClicked

    private void buttonDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseEntered
        if (!paneMain.getBackground().equals(new java.awt.Color(240, 240, 240))) {
            paneMain.setBackground(new java.awt.Color(250, 250, 250)); 
            panelLain.setBackground(new java.awt.Color(0, 102, 153));
        }
    }//GEN-LAST:event_buttonDashboardMouseEntered

    private void buttonDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseExited
        if (!menuActive.equals("dashboard")) {
            paneMain.setBackground(new java.awt.Color(0, 204, 204));
            panelLain.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_buttonDashboardMouseExited

    private void paneMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneMainMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_paneMainMousePressed

    private void buttonOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOrderMouseClicked
        // TODO add your handling code here:      
        menuActive = "order"; 
        resetWarna();
        paneMain1.setBackground(new java.awt.Color(250, 250, 250));
        panelLain1.setBackground(new java.awt.Color(0, 102, 153));

        jPanel5.removeAll(); 
        jPanel5.setLayout(new java.awt.BorderLayout()); 

        jPanel5.add(new halamanJadwalkanDokter(), java.awt.BorderLayout.CENTER);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_buttonOrderMouseClicked

    private void buttonOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOrderMouseEntered
        // TODO add your handling code here:
        if (!paneMain1.getBackground().equals(new java.awt.Color(240, 240, 240))) {
            paneMain1.setBackground(new java.awt.Color(250, 250, 250));
            panelLain1.setBackground(new java.awt.Color(0, 102, 153));
        }
    }//GEN-LAST:event_buttonOrderMouseEntered

    private void buttonOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOrderMouseExited
        // TODO add your handling code here:
        if (!menuActive.equals("order")) {
            paneMain1.setBackground(new java.awt.Color(0, 204, 204));
            panelLain1.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_buttonOrderMouseExited

    private void buttonJadwalDokterAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_buttonJadwalDokterAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonJadwalDokterAncestorAdded

    private void buttonJadwalDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonJadwalDokterMouseClicked
        // TODO add your handling code here:
        menuActive = "jadwal"; 
        resetWarna();
        paneMain2.setBackground(new java.awt.Color(250, 250, 250));
        panelLain2.setBackground(new java.awt.Color(0, 102, 153));
        
        jPanel5.removeAll(); 
        jPanel5.setLayout(new java.awt.BorderLayout()); 
        jPanel5.add(new halamanInfoPesanan(), java.awt.BorderLayout.CENTER);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_buttonJadwalDokterMouseClicked

    private void buttonJadwalDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonJadwalDokterMouseEntered
        // TODO add your handling code here:
        if (!paneMain2.getBackground().equals(new java.awt.Color(240, 240, 240))) {
            paneMain2.setBackground(new java.awt.Color(250, 250, 250));
            panelLain2.setBackground(new java.awt.Color(0, 102, 153));
        }
    }//GEN-LAST:event_buttonJadwalDokterMouseEntered

    private void buttonJadwalDokterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonJadwalDokterMouseExited
        // TODO add your handling code here:
        if (!menuActive.equals("jadwal")) {
            paneMain2.setBackground(new java.awt.Color(0, 204, 204));
            panelLain2.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_buttonJadwalDokterMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        halamanLogin login = new halamanLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new halamanHomeAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonDashboard;
    private javax.swing.JLabel buttonJadwalDokter;
    private javax.swing.JLabel buttonOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel paneMain1;
    private javax.swing.JPanel paneMain2;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelLain;
    private javax.swing.JPanel panelLain1;
    private javax.swing.JPanel panelLain2;
    // End of variables declaration//GEN-END:variables
}
