/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class menuPemesananJanjiTemu extends javax.swing.JPanel {
    /**
     * Creates new form menuPemesananJanjiTemu
     */   
    private javax.swing.JPanel selectedPanel = null;
    
    public menuPemesananJanjiTemu() {
        initComponents();
        jTextField1.setEditable(false);
        loadTableData();
        updateJadwalCard();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelSmith = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelAlex = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelAndrew = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelFermino = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelSinta = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelMiska = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelRobert = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelAlena = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-create-order.gif"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Pemesanan Janji Temu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("  Jadwalkan Konsultasi Anda !!!");

        panelSmith.setBackground(new java.awt.Color(255, 255, 255));
        panelSmith.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSmithMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSmithMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSmithMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Dr Smith");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Jadwal :");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelSmithLayout = new javax.swing.GroupLayout(panelSmith);
        panelSmith.setLayout(panelSmithLayout);
        panelSmithLayout.setHorizontalGroup(
            panelSmithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSmithLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSmithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelSmithLayout.setVerticalGroup(
            panelSmithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSmithLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAlex.setBackground(new java.awt.Color(255, 255, 255));
        panelAlex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAlexMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAlexMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAlexMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Dr Alex");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Jadwal :");

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelAlexLayout = new javax.swing.GroupLayout(panelAlex);
        panelAlex.setLayout(panelAlexLayout);
        panelAlexLayout.setHorizontalGroup(
            panelAlexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelAlexLayout.setVerticalGroup(
            panelAlexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAndrew.setBackground(new java.awt.Color(255, 255, 255));
        panelAndrew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAndrewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAndrewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAndrewMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Dr Andrew");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Jadwal :");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelAndrewLayout = new javax.swing.GroupLayout(panelAndrew);
        panelAndrew.setLayout(panelAndrewLayout);
        panelAndrewLayout.setHorizontalGroup(
            panelAndrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAndrewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAndrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelAndrewLayout.setVerticalGroup(
            panelAndrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAndrewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFermino.setBackground(new java.awt.Color(255, 255, 255));
        panelFermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFerminoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFerminoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFerminoMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Dr Fermino");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Jadwal :");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelFerminoLayout = new javax.swing.GroupLayout(panelFermino);
        panelFermino.setLayout(panelFerminoLayout);
        panelFerminoLayout.setHorizontalGroup(
            panelFerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFerminoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFerminoLayout.setVerticalGroup(
            panelFerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFerminoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSinta.setBackground(new java.awt.Color(255, 255, 255));
        panelSinta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSintaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSintaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSintaMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Dr Sinta");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Jadwal :");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelSintaLayout = new javax.swing.GroupLayout(panelSinta);
        panelSinta.setLayout(panelSintaLayout);
        panelSintaLayout.setHorizontalGroup(
            panelSintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSintaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelSintaLayout.setVerticalGroup(
            panelSintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSintaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMiska.setBackground(new java.awt.Color(255, 255, 255));
        panelMiska.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMiskaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMiskaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMiskaMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Dr Miska");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Jadwal :");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelMiskaLayout = new javax.swing.GroupLayout(panelMiska);
        panelMiska.setLayout(panelMiskaLayout);
        panelMiskaLayout.setHorizontalGroup(
            panelMiskaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMiskaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMiskaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelMiskaLayout.setVerticalGroup(
            panelMiskaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMiskaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Lakukan Pemesanan ");

        jLabel22.setText("Catatan Keluhan");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel30.setText("Nama");

        jLabel31.setText("NIM");

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(" Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Kirim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jam", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menit", "00", "10", "20", "30", "40", "50", " " }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel25)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRobert.setBackground(new java.awt.Color(255, 255, 255));
        panelRobert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRobertMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRobertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRobertMouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Dr Robert");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Jadwal :");

        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("hari, jam mulai - jam selesai");

        javax.swing.GroupLayout panelRobertLayout = new javax.swing.GroupLayout(panelRobert);
        panelRobert.setLayout(panelRobertLayout);
        panelRobertLayout.setHorizontalGroup(
            panelRobertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRobertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRobertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelRobertLayout.setVerticalGroup(
            panelRobertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRobertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAlena.setBackground(new java.awt.Color(255, 255, 255));
        panelAlena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAlenaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAlenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAlenaMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Dr Alena");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Jadwal :");

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Senin 16:00-20:00 WIB");

        javax.swing.GroupLayout panelAlenaLayout = new javax.swing.GroupLayout(panelAlena);
        panelAlena.setLayout(panelAlenaLayout);
        panelAlenaLayout.setHorizontalGroup(
            panelAlenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        panelAlenaLayout.setVerticalGroup(
            panelAlenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Keluhan", "Haril", "Waktu", "Dokter", "Keterangan"
            }
        ));
        jTable2.setEnabled(false);
        jTable2.setRowHeight(40);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelSmith, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelFermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelAlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelSinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelAndrew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelMiska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelAlena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelRobert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelSmith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelAlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelAlena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelAndrew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRobert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMiska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void panelSmithMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSmithMouseClicked
        // TODO add your handling code here:
        updateSelection(panelSmith);
    }//GEN-LAST:event_panelSmithMouseClicked

    private void panelSmithMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSmithMouseEntered
        // TODO add your handling code here:
        setHover(panelSmith);
    }//GEN-LAST:event_panelSmithMouseEntered

    private void panelSmithMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSmithMouseExited
        // TODO add your handling code here:
        setReset(panelSmith);
    }//GEN-LAST:event_panelSmithMouseExited

    private void panelFerminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFerminoMouseClicked
        // TODO add your handling code here:
         updateSelection(panelFermino);
    }//GEN-LAST:event_panelFerminoMouseClicked

    private void panelFerminoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFerminoMouseEntered
        // TODO add your handling code here:
        setHover(panelFermino);
    }//GEN-LAST:event_panelFerminoMouseEntered

    private void panelFerminoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFerminoMouseExited
        // TODO add your handling code here:
        setReset(panelFermino);
    }//GEN-LAST:event_panelFerminoMouseExited

    private void panelAlexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlexMouseClicked
        // TODO add your handling code here:
        updateSelection(panelAlex);
    }//GEN-LAST:event_panelAlexMouseClicked

    private void panelAlexMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlexMouseEntered
        // TODO add your handling code here:
        setHover(panelAlex);
    }//GEN-LAST:event_panelAlexMouseEntered

    private void panelAlexMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlexMouseExited
        // TODO add your handling code here:
        setReset(panelAlex);
    }//GEN-LAST:event_panelAlexMouseExited

    private void panelSintaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSintaMouseClicked
        // TODO add your handling code here:
        updateSelection(panelSinta);
    }//GEN-LAST:event_panelSintaMouseClicked

    private void panelSintaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSintaMouseEntered
        // TODO add your handling code here:
        setHover(panelSinta);
    }//GEN-LAST:event_panelSintaMouseEntered

    private void panelSintaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSintaMouseExited
        // TODO add your handling code here:
        setReset(panelSinta);
    }//GEN-LAST:event_panelSintaMouseExited

    private void panelAndrewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAndrewMouseClicked
        // TODO add your handling code here:
        updateSelection(panelAndrew);
    }//GEN-LAST:event_panelAndrewMouseClicked

    private void panelAndrewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAndrewMouseEntered
        // TODO add your handling code here:
        setHover(panelAndrew);
    }//GEN-LAST:event_panelAndrewMouseEntered

    private void panelAndrewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAndrewMouseExited
        // TODO add your handling code here:
        setReset(panelAndrew);
    }//GEN-LAST:event_panelAndrewMouseExited

    private void panelMiskaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiskaMouseClicked
        // TODO add your handling code here:
        updateSelection(panelMiska);
    }//GEN-LAST:event_panelMiskaMouseClicked

    private void panelMiskaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiskaMouseEntered
        // TODO add your handling code here:
        setHover(panelMiska);
    }//GEN-LAST:event_panelMiskaMouseEntered

    private void panelMiskaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiskaMouseExited
        // TODO add your handling code here:
        setReset(panelMiska);
    }//GEN-LAST:event_panelMiskaMouseExited

    private void panelAlenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlenaMouseClicked
        // TODO add your handling code here:
        updateSelection(panelAlena);
    }//GEN-LAST:event_panelAlenaMouseClicked

    private void panelAlenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlenaMouseEntered
        // TODO add your handling code here:
        setHover(panelAlena);
    }//GEN-LAST:event_panelAlenaMouseEntered

    private void panelAlenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlenaMouseExited
        // TODO add your handling code here:
        setReset(panelAlena);
    }//GEN-LAST:event_panelAlenaMouseExited

    private void panelRobertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRobertMouseClicked
        // TODO add your handling code here:
        updateSelection(panelRobert);
    }//GEN-LAST:event_panelRobertMouseClicked

    private void panelRobertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRobertMouseEntered
        // TODO add your handling code here:
        setHover(panelRobert);
    }//GEN-LAST:event_panelRobertMouseEntered

    private void panelRobertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRobertMouseExited
        // TODO add your handling code here:
        setReset(panelRobert);
    }//GEN-LAST:event_panelRobertMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (selectedPanel == null) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih Dokter terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Date tanggalDipilih = jDateChooser1.getDate();
        String jam = jComboBox1.getSelectedItem().toString();
        String menit = jComboBox2.getSelectedItem().toString().trim(); 
        if (tanggalDipilih == null) {
            JOptionPane.showMessageDialog(this, "Mohon pilih tanggal pada kalender!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jam.equals("Jam") || menit.equals("Menit") || menit.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon tentukan Jam dan Menit konsultasi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SimpleDateFormat sdfHari = new SimpleDateFormat("EEEE", new Locale("id", "ID"));
        String hariPilihanUser = sdfHari.format(tanggalDipilih);
        String hariWajibDokter = getHariWajibDokter();

        if (!hariPilihanUser.equalsIgnoreCase(hariWajibDokter)) {
            JOptionPane.showMessageDialog(this, 
                "Maaf, Dokter ini hanya praktik pada hari " + hariWajibDokter + ".\n" +
                "Anda memilih hari " + hariPilihanUser + ".", 
                "Jadwal Hari Tidak Sesuai", JOptionPane.ERROR_MESSAGE);
            jTextField1.setText("");
            return; 
        }
        boolean isJamValid = cekValidasiJam(jam, menit);

        if (!isJamValid) {
            String jadwalJam = getDokterInfo()[1]; 
            JOptionPane.showMessageDialog(this, 
                "Maaf, Jam yang Anda pilih di luar jam praktik dokter.\n" +
                "Jadwal Praktik: " + jadwalJam + "\n" +
                "Pilihan Anda: " + jam + ":" + menit,
                "Jam Tidak Sesuai", JOptionPane.ERROR_MESSAGE);
            jTextField1.setText(""); 
            return;
        }
        SimpleDateFormat sdfLengkap = new SimpleDateFormat("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
        String strTanggal = sdfLengkap.format(tanggalDipilih);
        String strWaktu = jam + ":" + menit + " WIB";
        String hasilAkhir = strTanggal + " | " + strWaktu;
        jTextField1.setText(hasilAkhir);
        JOptionPane.showMessageDialog(this, "Jadwal Berhasil Disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String inputLengkap = jTextField1.getText(); 
        String nama = jTextField2.getText();
        String nim = jTextField4.getText();
        String keluhan = jTextArea1.getText();

        if (selectedPanel == null || inputLengkap.isEmpty() || nama.isEmpty() || nim.isEmpty() || keluhan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data (Dokter, Jadwal, Nama, NIM, Keluhan)!", "Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String hariSaja = "";
        String waktuSpesifik = "";

        if (inputLengkap.contains("|")) {
            String[] parts = inputLengkap.split(" \\| "); 
            String bagianTanggal = parts[0]; 
            waktuSpesifik = parts[1];        
            hariSaja = bagianTanggal.split(",")[0];
        } else {
            hariSaja = inputLengkap;
            waktuSpesifik = getDokterInfo()[1]; 
        }

        String namaDokter = getDokterInfo()[0];

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{
            nama,   
            keluhan,        
            hariSaja,       
            waktuSpesifik,  
            namaDokter,     
            "Menunggu"      
        });

        if (userData.currentUser != null) {
         userData.Appointment newApp = new userData.Appointment();

         newApp.namaPasien = nama;
         newApp.nim = nim;
         newApp.keluhan = keluhan;
         newApp.hari = hariSaja;       
         newApp.waktu = waktuSpesifik; 
         newApp.dokter = namaDokter;
         newApp.status = "Menunggu";   

         userData.currentUser.appointments.add(newApp);

         userData.allAppointments.add(newApp);
         
         if (userData.currentUser != null) {
                String pesanSingkat = "Pesanan Terkirim";
                String detailPesan = "Pesanan janji temu Anda telah berhasil dikirim ke sistem.\nMohon tunggu konfirmasi dokter.";
                userData.currentUser.notifications.add(new userData.Notification(pesanSingkat, detailPesan));
            }
        }

        JOptionPane.showMessageDialog(this, "Janji Temu Berhasil Dibuat!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextArea1.setText("");
        jDateChooser1.setDate(null);
        jComboBox1.setSelectedIndex(0); 
        jComboBox2.setSelectedIndex(0); 

        if (selectedPanel != null) {
            selectedPanel.setBackground(new java.awt.Color(255, 255, 255));
            selectedPanel = null;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int jawaban = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin membatalkan dan menghapus semua isian?", 
                "Konfirmasi Batal", 
                JOptionPane.YES_NO_OPTION);
        if (jawaban == JOptionPane.YES_OPTION) {
            jTextField1.setText(""); 
            jTextField2.setText(""); 
            jTextField4.setText(""); 
            jTextArea1.setText("");  
            jDateChooser1.setDate(null);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);

            if (selectedPanel != null) { 
                selectedPanel.setBackground(new java.awt.Color(255, 255, 255));              
                selectedPanel = null;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateSelection(javax.swing.JPanel panel) {
        if (selectedPanel != null) {
            selectedPanel.setBackground(new java.awt.Color(255, 255, 255));
        }    
        selectedPanel = panel;
        selectedPanel.setBackground(new java.awt.Color(0, 153, 153));
    }
    private void setHover(javax.swing.JPanel panel) {
        if (panel != selectedPanel) {
            panel.setBackground(new java.awt.Color(240, 240, 240)); // Abu-abu muda
        }
    }
    private void setReset(javax.swing.JPanel panel) {
        if (panel != selectedPanel) {
            panel.setBackground(new java.awt.Color(255, 255, 255));
        }
    }
    private void loadTableData() {
        if (userData.currentUser != null) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
            model.setRowCount(0); 
            for (userData.Appointment app : userData.currentUser.appointments) {
                model.addRow(new Object[]{
                    app.namaPasien,
                    app.keluhan,
                    app.hari,
                    app.waktu,
                    app.dokter,
                    app.status
                });
            }
        }
    }
    
    private String[] getDokterInfo() {
       String namaDokter = "";
        if (selectedPanel == panelSmith) namaDokter = "Dr Smith";
        else if (selectedPanel == panelAlex) namaDokter = "Dr Alex";
        else if (selectedPanel == panelAndrew) namaDokter = "Dr Andrew";
        else if (selectedPanel == panelFermino) namaDokter = "Dr Fermino";
        else if (selectedPanel == panelSinta) namaDokter = "Dr Sinta";
        else if (selectedPanel == panelMiska) namaDokter = "Dr Miska";
        else if (selectedPanel == panelAlena) namaDokter = "Dr Alena";
        else if (selectedPanel == panelRobert) namaDokter = "Dr Robert";

        String jamPraktik = "";
        boolean found = false;
        if (userData.listJadwal != null) {
            for (userData.JadwalDokter jd : userData.listJadwal) {
                if (jd.namaDokter.equals(namaDokter)) {                  
                    jamPraktik = jd.jamMulai + "-" + jd.jamSelesai + " WIB";
                    found = true;
                    break;
                }
            }
        }
        if (!found) {
            if (namaDokter.equals("Dr Alena") || namaDokter.equals("Dr Robert")) {
                jamPraktik = "16:00-20:00 WIB";
            } else {
                jamPraktik = "08:00-15:00 WIB";
            }
        }
        return new String[]{namaDokter, jamPraktik};
    }
    private String getHariWajibDokter() {
        String namaDokter = "";
        if (selectedPanel == panelSmith) namaDokter = "Dr Smith";
        else if (selectedPanel == panelAlex) namaDokter = "Dr Alex";
        else if (selectedPanel == panelAndrew) namaDokter = "Dr Andrew";
        else if (selectedPanel == panelFermino) namaDokter = "Dr Fermino";
        else if (selectedPanel == panelSinta) namaDokter = "Dr Sinta";
        else if (selectedPanel == panelMiska) namaDokter = "Dr Miska";
        else if (selectedPanel == panelAlena) namaDokter = "Dr Alena";
        else if (selectedPanel == panelRobert) namaDokter = "Dr Robert";

        for (userData.JadwalDokter jd : userData.listJadwal) {
            if (jd.namaDokter.equals(namaDokter)) {
                return jd.hari;
            }
        }
        if (namaDokter.equals("Dr Smith")) return "Senin";
        return null;
    }
    private boolean cekValidasiJam(String jamStr, String menitStr) {
        int jam = Integer.parseInt(jamStr);
        int menit = Integer.parseInt(menitStr.trim());
        
        String namaDokter = "";
        if (selectedPanel == panelSmith) namaDokter = "Dr Smith";
        else if (selectedPanel == panelAlex) namaDokter = "Dr Alex";
        else if (selectedPanel == panelAndrew) namaDokter = "Dr Andrew";
        else if (selectedPanel == panelFermino) namaDokter = "Dr Fermino";
        else if (selectedPanel == panelSinta) namaDokter = "Dr Sinta";
        else if (selectedPanel == panelMiska) namaDokter = "Dr Miska";
        else if (selectedPanel == panelAlena) namaDokter = "Dr Alena";
        else if (selectedPanel == panelRobert) namaDokter = "Dr Robert";

        int jamMulai = 0;
        int jamSelesai = 0;

        boolean found = false;
        for (userData.JadwalDokter jd : userData.listJadwal) {
            if (jd.namaDokter.equals(namaDokter)) {              
                jamMulai = Integer.parseInt(jd.jamMulai.substring(0, 2));
                jamSelesai = Integer.parseInt(jd.jamSelesai.substring(0, 2));
                found = true;
                break;
            }
        }
        if (!found) {
            if (selectedPanel == panelAlena || selectedPanel == panelRobert) {
                jamMulai = 16; jamSelesai = 20;
            } else {
                jamMulai = 8; jamSelesai = 15;
            }
        }
        if (jam < jamMulai || jam > jamSelesai) return false;
        if (jam == jamSelesai && menit > 0) return false;
        return true;
    }
    private void updateJadwalCard() {
    if (userData.listJadwal != null && !userData.listJadwal.isEmpty()) {        
        for (userData.JadwalDokter jd : userData.listJadwal) {
            String infoJadwal = jd.hari + " " + jd.jamMulai + "-" + jd.jamSelesai + " WIB";         
            switch (jd.namaDokter) {
                case "Dr Smith":
                    jLabel6.setText(infoJadwal); 
                    break;
                case "Dr Alex":
                    jLabel9.setText(infoJadwal);
                    break;
                case "Dr Andrew":
                    jLabel12.setText(infoJadwal); 
                    break;
                case "Dr Fermino":
                    jLabel15.setText(infoJadwal); 
                    break;
                case "Dr Sinta":
                    jLabel18.setText(infoJadwal); 
                    break;
                case "Dr Miska":
                    jLabel21.setText(infoJadwal); 
                    break;
                case "Dr Robert":
                    jLabel26.setText(infoJadwal); 
                    break;
                case "Dr Alena":
                    jLabel29.setText(infoJadwal); 
                    break;
            }
        }
    }
}
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelAlena;
    private javax.swing.JPanel panelAlex;
    private javax.swing.JPanel panelAndrew;
    private javax.swing.JPanel panelFermino;
    private javax.swing.JPanel panelMiska;
    private javax.swing.JPanel panelRobert;
    private javax.swing.JPanel panelSinta;
    private javax.swing.JPanel panelSmith;
    // End of variables declaration//GEN-END:variables
}
